### ISSUE TITLE
getTrades() error

### ISSUE THREAD

**Issue by tsvetiligo** [ErhoSen/gas-tinkoff-trades#1]
=getTrades() return _"TypeError: Cannot destructure property 'figi' of 'tinkoffClient.getInstrumentByTicker(...)' as it is undefined. (line 58)."_
=getTrades("AAPL") return _"TypeError: Cannot read property 'value' of undefined (line 108)."_

**Comment by erhosen** [comment]
Хз отчего так происходит. Видимо Tinkoff изменил API

Как будет время посмотрю

**Comment by dandelio** [comment]
Может быть у них временный глюк. Так то работает скрипт

**Comment by glemag** [comment]
Подтверждаю ошибку, TypeError: Cannot destructure property 'figi' of 'tinkoffClient.getInstrumentByTicker(...)' as it is undefined. (строка 60).

**Comment by erhosen** [comment]
> Подтверждаю ошибку, TypeError: Cannot destructure property 'figi' of 'tinkoffClient.getInstrumentByTicker(...)' as it is undefined. (строка 60).

А на каком тикере у вас такое поведение?

**Comment by glemag** [comment]
Как это проверить?

**Comment by glemag** [comment]
Я со своей стороны доработал таблицу по статье вот отсюда https://habr.com/ru/post/516210/ разделил отдельные операции по вкладкам + добавил получение курса валют от ЦБРФ и снятие комиссий по валюте на указанную дату, +на главную страницу портфеля вывел всю информацию о комиссиях, налогах, дивидендах за указанный период.

**Comment by erhosen** [comment]
> Как это проверить?

Ну если у вас метод `getInstrumentByTicker` завершается с ошибкой - я бы хотел это воспроизвести. Для этого мне нужен тикер (например 'AAPL`) который вы запрашиваете в своей таблице.

Посмотреть его можно кликнув на ячейку в окне с формулой, которая завершилась **!ERROR#**

 
![image](https://user-images.githubusercontent.com/5013076/120920104-dc312f80-c6c5-11eb-94c1-96fbd707e634.png)

**Comment by TimurTsedik** [comment]
Ошибка возникает в строке
    const response = UrlFetchApp.fetch(url, params)

Выдает ошибку 403. Я так понимаю это HTTP Forbidden

Токены переформировавал раз 10, безрезультатно. Вчера и сегодня одна и та же ошибка

Тикеры - GAZP, LKOH, BELU

можно любые пробовать

**Comment by erhosen** [comment]
Там у товарища была совсем другая ошибка 

Double: https://github.com/ErhoSen/gas-tinkoff-trades/issues/5
