### ISSUE TITLE
TI_GetLastPrice() и другие функции, зависящие от функций API v1 не работают с токенами только для чтения

### ISSUE THREAD

**Issue by IVNXPTRVOLD** [ErhoSen/gas-tinkoff-trades#11]
Возвращает вот такую ошибку: 
`Exception: Request failed for https://api-invest.tinkoff.ru returned code 403 (line 48).`

**Comment by erhosen** [comment]
403 - ошибка доступа (Forbidden). Вы точно указали свой токен в настройках?

**Comment by IVNXPTRVOLD** [comment]
Да, с токеном все в порядке. TI_GetPortfolio() работает корректно

**Comment by HiHat** [comment]
Возможно, срабатывает защита API от слишком частых запросов...

**Comment by IVNXPTRVOLD** [comment]
Больше никаких запросов не даю, буквально один по одному тикеру

**Comment by GrKoR** [comment]
Подтверждаю.

getPriceByTicker(ticker)  и TI_GetLastPrice(ticker) выдают ошибку 403.

TI_GetAccounts(), TI_GetOperations(id), TI_GetPortfolio(id) отрабатывают корректно.

Ошибка может быть связана с тем, что Price берется по апи v1.
Ещё как вариант, что у токена права только для чтения (без права торговли). Но с какого перепуга получение цены должно попадать под ограничение прав на торговлю - ХЗ.

**Comment by HiHat** [comment]
Похоже readonly токены не работают со старым API :(
Через старый API идет поиск FIGI инструмента по тикеру. Видимо пришло время переходить на запросы по FIGI...
Надо будет добавить методы. FIGI можно будет получать поиском через VLOOKUP по отдельной вкладке с информацией по всем инструментам, полученной вызовом TI_GetInstrumentsID().

**Comment by HiHat** [comment]
Добавил TI_GetLastPriceByFigi()

**Comment by GrKoR** [comment]
Да, так работает, проверил.
Правда, остальные функции (например getTrades) всё равно отправляют запрос через тикер через метод класса tinkoffClient.getInstrumentByTicker(ticker) и валятся с той же ошибкой.

Насчет перехода на запросы по FIGI... А нельзя при создании экземпляра класса TinkoffClient в кеш выгружать данные, получаемые от TI_GetInstrumentsID? Какие ограничения на кеш у скрипта? Тогда не нужен будет отдельный лист с этой таблицей. И все преобразования TICKER <=> FIGI можно будет по данным кеша делать.

**Comment by HiHat** [comment]
Все функции без префикса TI_ сделаны для старого API и очевидно, что работать не будут. Завел Issue для старого API (https://github.com/Tinkoff/investAPI/issues/389), но, скорее всего, не будут чинить, т.к. уже не первый раз отвечают, чтобы переходили на новый API.
Выгружать информацию по FIGI в кэш особого смысла нет, т.к. в текущей выгрузке около 3500 инструментов, кэш это ассоциативный массив и все это будет очень не оптимально.
Ничего лучше отдельного листа пока не придумал...

**Comment by PozhidaevGM** [comment]
> Выгружать информацию по FIGI в кэш особого смысла нет, т.к. в текущей выгрузке около 3500 инструментов, кэш это ассоциативный массив и все это будет очень не оптимально.
> Ничего лучше отдельного листа пока не придумал...
1) кэш в GAS ограничен 1000 записей, так что грузить это в кэш не получится [https://developers.google.com/apps-script/reference/cache/cache#putkey,-value](url)
2) сбор всех instruments у меня занял 4-5 секунд, если с опционами, то на 4 секунды дольше, так что думаю перед затратными операциями вполне можно сначала выгрузить в свой массив с блэк-джэком, а потом искать в нём как захочется:
![image](https://user-images.githubusercontent.com/123592795/215868355-c9fcd9c7-b229-4d9d-9bc9-4464558d3ec0.png)

**Comment by xakauga** [comment]
Простите, не очень хорошо разбираюсь в гугл таблицах.
Помогите, пожалуйста, что значит "В эту ячейку по команде меню TI->Обновить вставляется текущая дата". Поясните, пожалуйста, что нужно сделать пошагово?

**Comment by HiHat** [comment]
> Простите, не очень хорошо разбираюсь в гугл таблицах. Помогите, пожалуйста, что значит "В эту ячейку по команде меню TI->Обновить вставляется текущая дата". Поясните, пожалуйста, что нужно сделать пошагово?

Надо выбрать любую неиспользуемую/ненужную ячейку и дать ей имя UPDATE_DATE. После этого по команде из меню  TI->Обновить в эту ячейку будет вставляться текущая дата. Добавив ссылку на эту ячейку к функциям получения данных получаем возможность обновлять их по команде из меню.
Например, при использовании функции TI_GetLastPrice("GAZP",UPDATE_DATE)) можно реализовать обновление цены по команде меню Обновить.

**Comment by HiHat** [comment]
Необходимо отказываться от работы по тикерам и переходить на работу через FIGI (функцию TI_GetLastPriceByFigi())
