### ISSUE TITLE
Пофиксил function TI_GetAccounts(accountType)  Не умею гитхабом пользоваться :(

### ISSUE THREAD

**Issue by Janoromix** [ErhoSen/gas-tinkoff-trades#14]
/**
 * Returns the ID of a Tinkoff account based on the input parameter.
 * @param {number} accountType - The type of account to retrieve. 
 * 0 - Брокерский счет
 * 1 - ИИС
 * 2 - Инвестиционная копилка (работает только с операциями)
 * @return {string} The ID of the selected account.
 */
function TI_GetAccounts(accountType) {
  const data = tinkoffClientV2._GetAccounts()

  switch (accountType) {
    case 0:
      return data.accounts[0].id;
    case 1:
      return data.accounts[1].id;
    case 2:
      return data.accounts[2].id;
    default:
      return "Не выбран портфель!";
  }
}

**Comment by HiHat** [comment]
Номера счетов не у всех соответствуют таким типам!
Изменю потом немного.

**Comment by HiHat** [comment]
Доработал TI_GetAccounts() и добавил TI_GetAccountID()
