### ISSUE TITLE
authentication token is missing or invalid code 40003

### ISSUE THREAD

**Issue by Chtets070** [ErhoSen/gas-tinkoff-trades#17]
Вставляю токен по инструкции в главе "установка", но возникает ошибка authentication token is missing or invalid code 40003 при выполнении функции TI_GetAccounts() или подобных:
Ошибка:
Exception: Request failed for https://invest-public-api.tinkoff.ru returned code 401. Truncated server response: {"code":16,"message":"authentication token is missing or invalid","description":"40003"} (use muteHttpExceptions option to examine full response)
_makeApiCall	@ TinkoffTrades_api_V2.gs:271
_GetAccounts	@ TinkoffTrades_api_V2.gs:351
TI_GetAccounts	@ TinkoffTrades_api_V2.gs:399

- Пробовал создавать токены с "только для чтения" и полный доступ
- Пытался создать отдельно на ИИС и брокерского счета
- "Подтверждение сделок кодом" в профиле тинькоф инвестиции выключен
- С чем может быть связана эта проблема?

**Comment by HiHat** [comment]
А времени сколько прошло после получения?
Иногда не сразу начинают работать.

**Comment by Chtets070** [comment]
Спасибо за обратную связь! не имею навыков программирования, поэтому сложно отловить проблему. 
прошло чуть больше 6 часов как создал токен.
как сказано в инструкции - вместо OPENAPI_TOKEN вставил свой токен с сохранением кавычек 'тут токен'
/** @OnlyCurrentDoc */

const scriptProperties = PropertiesService.getScriptProperties()
const OPENAPI_TOKEN = scriptProperties.getProperty('OPENAPI_TOKEN')

**Comment by HiHat** [comment]
Видимо неправильно создали параметр в настройках проекта.
Примерно так должно  быть:
![Снимок экрана 2023-06-30 в 22 23 42](https://github.com/ErhoSen/gas-tinkoff-trades/assets/2690010/f3a9708d-c3dc-4da4-8a0a-ebacda605672)

**Comment by Chtets070** [comment]
Спасибо! сейчас разобрался! так как впервые знакомился с apps script не знал что за шаг -
Добавить свойство OPENAPI_TOKEN в разделе Project properties -> Script properties равным токену, полученному выше.
