### ISSUE TITLE
поддержка APIv2

### ISSUE THREAD

**Issue by IntelOut** [ErhoSen/gas-tinkoff-trades#9]
Планируется поддержка и переработка на APIv2?

**Comment by erhosen** [comment]
Привет
Pull requests are much appreciated, как говорится :)

Мы с @HiHat знаем, что поддержка apiv1 скоро прекратится, но пока руки не доходят 🤷🏻‍♂️

**Comment by HiHat** [comment]
Добавил TI_GetLastPrice и TI_GetPortfolio.
Для получения figi по тикеру пока приходится использовать функцию из API v1 :)
